"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase/client";

type Invoice = Record<string, unknown>;
function money(v: unknown){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v??0));}
export default function Page(){
  const [rows,setRows]=useState<Invoice[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");await supabase.rpc("refresh_overdue_invoices");const r=await supabase.from("invoices").select("id,invoice_number,invoice_status,due_date,subtotal,tax_amount,amount_paid,reminder_status,next_follow_up_date,reminder_count,client_id,created_at").neq("invoice_status","paid").neq("invoice_status","void").order("due_date",{ascending:true});if(r.error){setError(r.error.message);setRows([])}else setRows((r.data??[]) as Invoice[]);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const total=useMemo(()=>rows.reduce((s,r)=>s+Math.max(Number(r.subtotal??0)+Number(r.tax_amount??0)-Number(r.amount_paid??0),0),0),[rows]);
  return <main className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-black uppercase tracking-wide text-bakerssPink">Collections</p><h1 className="mt-1 text-3xl font-black">Collections Follow-Up</h1><p className="mt-2 text-sm text-gray-600">Open invoices requiring collection follow-up, reminder tracking, or escalation.</p></div><div className="flex gap-2"><Link href="/invoices" className="rounded-xl border bg-white px-4 py-3 text-sm font-black">Invoices</Link><button onClick={()=>void load()} className="rounded-xl bg-black px-4 py-3 text-sm font-black text-white">Refresh</button></div></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}<section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-gray-500">Open Invoices</p><p className="mt-2 text-3xl font-black">{rows.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-gray-500">Open Balance</p><p className="mt-2 text-3xl font-black">{money(total)}</p></div></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center text-sm">Loading…</div>:rows.length===0?<div className="p-8 text-center text-sm text-gray-600">No open collection items.</div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Reminder</th><th className="px-4 py-3">Next Follow-Up</th><th></th></tr></thead><tbody className="divide-y">{rows.map(r=>{const bal=Math.max(Number(r.subtotal??0)+Number(r.tax_amount??0)-Number(r.amount_paid??0),0);return <tr key={String(r.id)}><td className="px-4 py-4 font-black">{String(r.invoice_number??"Invoice")}</td><td className="px-4 py-4">{String(r.invoice_status??"—")}</td><td className="px-4 py-4">{r.due_date?new Date(String(r.due_date)+"T00:00:00").toLocaleDateString():"—"}</td><td className="px-4 py-4 font-black">{money(bal)}</td><td className="px-4 py-4">{String(r.reminder_status??"not_started")}</td><td className="px-4 py-4">{r.next_follow_up_date?new Date(String(r.next_follow_up_date)+"T00:00:00").toLocaleDateString():"—"}</td><td className="px-4 py-4 text-right"><Link href={`/invoices/${String(r.id)}`} className="font-black text-bakerssPink">Open</Link></td></tr>})}</tbody></table></div>}</section></main>
}
