"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "../../../../lib/supabase/client";

type Metric={label:string;value:string;note:string;href:string};
export default function Page(){const [metrics,setMetrics]=useState<Metric[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);setError("");const tables=[
  ["recurring_billing_runs","Billing Runs","/invoices/recurring-billing/runs"],
  ["invoice_delivery_activity","Delivery Activity","/invoices/recurring-billing/delivery-history"],
  ["invoice_collection_activity","Collection Activity","/invoices/follow-up"],
  ["payment_exception_cases","Payment Exceptions","/invoices/payment-exceptions"],
  ["customer_credits","Customer Credits","/invoices/credits"],
  ["statement_delivery_activity","Statement Deliveries","/invoices/statements"],
] as const;const next:Metric[]=[];for(const [table,label,href] of tables){const r=await supabase.from(table).select("*",{count:"exact",head:true});if(r.error){setError((p)=>p?`${p}; ${label}: ${r.error?.message}`:`${label}: ${r.error?.message}`);next.push({label,value:"!",note:"Needs attention",href})}else next.push({label,value:String(r.count??0),note:"Live records",href})}setMetrics(next);setLoading(false)},[]);useEffect(()=>{void load()},[load]);return <main className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-black uppercase tracking-wide text-bakerssPink">Billing Automation</p><h1 className="mt-1 text-3xl font-black">Billing Operations</h1><p className="mt-2 text-sm text-gray-600">Operational overview of recurring billing, delivery, collections, credits, exceptions, and statement activity.</p></div><div className="flex gap-2"><Link href="/invoices/recurring-billing" className="rounded-xl border bg-white px-4 py-3 text-sm font-black">Recurring Billing</Link><button onClick={()=>void load()} className="rounded-xl bg-black px-4 py-3 text-sm font-black text-white">Refresh</button></div></header>{error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900">{error}</div>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{loading?<div className="rounded-2xl border bg-white p-5 text-sm">Loading operations…</div>:metrics.map(m=><Link href={m.href} key={m.label} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow"><p className="text-xs font-black uppercase text-gray-500">{m.label}</p><p className="mt-2 text-3xl font-black">{m.value}</p><p className="mt-1 text-xs text-gray-500">{m.note}</p></Link>)}</section><section className="rounded-2xl border bg-white p-6"><h2 className="text-lg font-black">Recovery Navigation</h2><div className="mt-4 flex flex-wrap gap-2">{[["Review","/invoices/recurring-billing/review"],["Release","/invoices/recurring-billing/release"],["Delivery","/invoices/recurring-billing/delivery"],["Delivery History","/invoices/recurring-billing/delivery-history"],["Runs","/invoices/recurring-billing/runs"],["QA","/invoices/recurring-billing/qa"]].map(([l,h])=><Link key={h} href={h} className="rounded-xl border px-4 py-3 text-sm font-black hover:bg-gray-50">{l}</Link>)}</div></section></main>}
